# Generated by Django 5.2.7 on 2026-02-27 22:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control_calidad', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Obra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=300)),
                ('descripcion', models.TextField(blank=True)),
                ('responsable', models.CharField(max_length=200)),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin_programada', models.DateField()),
                ('estado', models.CharField(choices=[('activo', 'Activo'), ('pausado', 'Pausado'), ('finalizado', 'Finalizado'), ('retrasado', 'Retrasado')], default='activo', max_length=20)),
            ],
            options={
                'verbose_name': 'Obra',
                'verbose_name_plural': 'Obras',
                'ordering': ['-fecha_inicio'],
            },
        ),
        migrations.CreateModel(
            name='FaseObra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('avance_programado', models.DecimalField(decimal_places=1, default=0, max_digits=5)),
                ('avance_real', models.DecimalField(decimal_places=1, default=0, max_digits=5)),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin_programada', models.DateField()),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('en_progreso', 'En Progreso'), ('completada', 'Completada'), ('retrasada', 'Retrasada')], default='pendiente', max_length=20)),
                ('obra', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fases', to='control_calidad.obra')),
            ],
            options={
                'verbose_name': 'Fase de Obra',
                'verbose_name_plural': 'Fases de Obra',
                'ordering': ['fecha_inicio'],
            },
        ),
    ]
