# Generated by Django 5.2.7 on 2026-02-27 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control_calidad', '0002_obra_faseobra'),
    ]

    operations = [
        migrations.CreateModel(
            name='Indicador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=300)),
                ('area', models.CharField(max_length=200)),
                ('formula', models.TextField(blank=True)),
                ('responsable', models.CharField(max_length=200)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10)),
                ('meta', models.DecimalField(decimal_places=2, max_digits=10)),
                ('unidad', models.CharField(blank=True, default='%', max_length=50)),
                ('mejor_al', models.CharField(choices=[('alza', 'Alza'), ('baja', 'Baja')], default='alza', max_length=10)),
                ('tendencia', models.CharField(choices=[('alza', 'Alza'), ('baja', 'Baja'), ('estable', 'Estable')], default='estable', max_length=10)),
                ('incluir_historico', models.BooleanField(default=True)),
                ('tabla_dinamica', models.BooleanField(default=False)),
                ('fecha_registro', models.DateField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Indicador',
                'verbose_name_plural': 'Indicadores',
                'ordering': ['area', 'nombre'],
            },
        ),
    ]
