# Generated by Django 5.2.7 on 2026-02-28 05:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control_calidad', '0003_indicador'),
    ]

    operations = [
        migrations.CreateModel(
            name='Competencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=300)),
                ('descripcion', models.TextField(blank=True)),
                ('area', models.CharField(max_length=200)),
                ('responsable', models.CharField(max_length=200)),
                ('nivel_requerido', models.PositiveSmallIntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], default=3)),
                ('nivel_actual', models.PositiveSmallIntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], default=1)),
                ('estado', models.CharField(choices=[('vigente', 'Vigente'), ('por_vencer', 'Por Vencer'), ('vencida', 'Vencida')], default='vigente', max_length=15)),
                ('fecha_evaluacion', models.DateField()),
                ('fecha_vencimiento', models.DateField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Competencia',
                'verbose_name_plural': 'Competencias',
                'ordering': ['area', 'nombre'],
            },
        ),
        migrations.CreateModel(
            name='Auditoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=300)),
                ('tipo', models.CharField(choices=[('interna', 'Interna'), ('externa', 'Externa')], default='interna', max_length=10)),
                ('estado', models.CharField(choices=[('programada', 'Programada'), ('en_curso', 'En Curso'), ('finalizada', 'Finalizada'), ('cancelada', 'Cancelada')], default='programada', max_length=15)),
                ('responsable', models.CharField(max_length=200)),
                ('fecha_programada', models.DateField()),
                ('fecha_realizacion', models.DateField(blank=True, null=True)),
                ('hallazgos_encontrados', models.PositiveIntegerField(default=0)),
                ('observaciones', models.TextField(blank=True)),
                ('proceso', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='auditorias', to='control_calidad.proceso')),
            ],
            options={
                'verbose_name': 'Auditoría',
                'verbose_name_plural': 'Auditorías',
                'ordering': ['-fecha_programada'],
            },
        ),
    ]
