# Generated by Django 5.2.7 on 2026-03-11 23:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control_calidad', '0004_competencia_auditoria'),
    ]

    operations = [
        migrations.CreateModel(
            name='Configuracion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_empresa', models.CharField(default='Mi Empresa', max_length=200)),
                ('descripcion', models.TextField(blank=True)),
                ('email_contacto', models.EmailField(blank=True, max_length=254)),
                ('logo_url', models.URLField(blank=True)),
            ],
            options={
                'verbose_name': 'Configuración',
                'verbose_name_plural': 'Configuración del Sistema',
            },
        ),
    ]
